name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.2, 8.3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist
          chmod +x vendor/bin/phpunit

      - name: Run tests
        run: |
          php -v  # Output PHP version for debugging
          composer diagnose  # Check for any composer issues
          vendor/bin/phpunit --configuration phpunit.xml --verbose
